### ISSUE TITLE
Unable to connect to the CloudflareWARP daemon

### ISSUE THREAD

**Issue by msTokens** [threatpatrols/docker-cfwarp-gost#1]
✔ Container socks-with-upstream     Created                                                                                      0.0s 
 ✔ Container socks-cloudflare-local  Created                                                                                      0.0s 
Attaching to socks-cloudflare-local, socks-with-upstream
socks-with-upstream     | cfwarp-gost: 2024-12-15T06:12:10+00:00
socks-with-upstream     | GOST_FORWARD=socks5://<socks-server-ip-address>:<socks-server-port>
socks-with-upstream     | DEBUG=1
socks-with-upstream     | WARP_CONNECT_RETRY_SLEEP=5
socks-with-upstream     | WARP_HEALTHCHECK_PING=1.1.1.1
socks-with-upstream     | WARP_CLIENT_ID=
socks-with-upstream     | WARP_START_DELAY=5
socks-with-upstream     | WARP_SYSTEM_STATUS_DELAY=90
socks-with-upstream     | WARP_CONNECT_RETRY_MAX=20
socks-with-upstream     | WARP_ORGANIZATION=
socks-with-upstream     | WARP_CONNECTOR_TOKEN=[redacted]
socks-with-upstream     | WARP_CLIENT_SECRET=[redacted]
socks-with-upstream     | WARP_LICENSE_KEY=[redacted]
socks-with-upstream     | 
socks-with-upstream     | 
socks-with-upstream     | + /scripts/warp-connect.sh
socks-with-upstream     | + /scripts/warp-system-status.sh 90
socks-with-upstream     |  >> [warp-system-status] waiting 90 seconds before running system status.
socks-cloudflare-local  | cfwarp-gost: 2024-12-15T06:12:10+00:00
socks-cloudflare-local  | GOST_FORWARD=
socks-cloudflare-local  | DEBUG=
socks-cloudflare-local  | WARP_CONNECT_RETRY_SLEEP=5
socks-cloudflare-local  | WARP_HEALTHCHECK_PING=1.1.1.1
socks-cloudflare-local  | WARP_CLIENT_ID=
socks-cloudflare-local  | WARP_START_DELAY=5
socks-cloudflare-local  | WARP_SYSTEM_STATUS_DELAY=90
socks-cloudflare-local  | WARP_CONNECT_RETRY_MAX=20
socks-cloudflare-local  | WARP_ORGANIZATION=
socks-cloudflare-local  | WARP_CONNECTOR_TOKEN=[redacted]
socks-cloudflare-local  | WARP_CLIENT_SECRET=[redacted]
socks-cloudflare-local  | WARP_LICENSE_KEY=[redacted]
socks-cloudflare-local  | 
socks-cloudflare-local  | 
socks-cloudflare-local  |  >> [warp-system-status] waiting 90 seconds before running system status.
socks-with-upstream     | 2024-12-15T06:12:10.763Z  INFO warp::warp_service: Starting WarpService pid=35
socks-with-upstream     | 2024-12-15T06:12:10.763Z  INFO warp::warp_service: Version: 2024.11.309.0
socks-with-upstream     | warp-cli 2024.11.309.0
socks-with-upstream     |  >> [warp-register] registering Warp client
socks-with-upstream     | Unable to connect to the CloudflareWARP daemon: No such file or directory (os error 2)
socks-with-upstream     | 
socks-with-upstream     | Maybe the daemon is not running?
socks-with-upstream     | 
socks-cloudflare-local  | warp-cli 2024.11.309.0
socks-cloudflare-local  |  >> [warp-register] registering Warp client
socks-cloudflare-local  | Unable to connect to the CloudflareWARP daemon: No such file or directory (os error 2)
socks-cloudflare-local  | 
socks-cloudflare-local  | Maybe the daemon is not running?
socks-cloudflare-local  | 
socks-cloudflare-local exited with code 0
socks-with-upstream exited with code 0

#Docker version 27.4.0, build bde2b89

**Comment by ndejong** [comment]
Thanks for the report, requires a package update to resolve CFWarp has been changing a fair bit recently - in the mean time you might find better luck with tag 0.1.7 or perhaps 0.2.0

**Comment by msTokens** [comment]
It works, the issue was the Firewall, i opened ingress for the Cloudflare IP's on all ports.

So if anyone has this issue. ITS YOUR FIREWALL!

Great job it works very well.

**Comment by ndejong** [comment]
Thanks for the followup report
