### ISSUE TITLE
WARP+ not working

### ISSUE THREAD

**Issue by msTokens** [threatpatrols/docker-cfwarp-gost#2]
Hello,

i have parsed the ENV
WARP_LICENSE_KEY = MYKEY

it appears on the ENV of the Docker Container, but it still goes with FREE.

I have for 5 devices premium why it does not register with Warp+ even if the ENV's are set right.

do we have a bug somewhere ?

**Comment by msTokens** [comment]
root@43ac4ce8f21a:/# warp-cli set-license XXXXXXXX
error: unrecognized subcommand 'set-license'

  tip: a similar subcommand exists: 'settings'

Usage: warp-cli [OPTIONS] <COMMAND>



i logged to the container seeps like the command you are using in your scripts has wrong  subcommands, please fix it.

**Comment by msTokens** [comment]
SOLUTION:

root@43ac4ce8f21a:/# warp-cli registration license
error: the following required arguments were not provided:
  <KEY>

Usage: warp-cli registration license <KEY>

warp-cli registration license < Implement this to the scripts after it disconnect command, after that it gets it.

Please fix your latest version thank you.

**Comment by ndejong** [comment]
Thanks for the report and taking the time to determine the underlaying issue - should be fixed in `0.2.2`
